services:

  # ── PRODUCTS ──────────────────────────────────────────────
  products-db:
    image: postgres:15
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  products-service:
    build: ./products-service
    ports:
      - "8001:8000"
    env_file:
      - ./products-service/.env
    depends_on:
      - products-db

  # ── ORDERS ────────────────────────────────────────────────
  orders-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  orders-service:
    build: ./orders-service
    ports:
      - "8002:8000"
    env_file:
      - ./orders-service/.env
    depends_on:
      - orders-db
      - products-service

  # ── PAYMENTS ──────────────────────────────────────────────
  payments-db:
    image: postgres:15
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  payments-service:
    build: ./payments-service
    ports:
      - "8003:8000"
    env_file:
      - ./payments-service/.env
    depends_on:
      - payments-db
      - orders-service